# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5515376287a5af9e1dd55c5527b8ccf020c7275237882c9cac17e86c64b562d1e56da1826bcdae76fb0e46c178aa5d07b7b5e3cb62c52a926eec36f4222dbdb

test:
  secret_key_base: 10db4f94f770ee23cd21ce5640f06137e695be966468e2675b865f6058df814219ec17723bd948c303bfb242c7e79aead1ab4f4f5092b8e56d0d75096117ae9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
